<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViewVb</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;Win32</Platforms>
    <RootNamespace>ViewVb</RootNamespace>
    <TargetFrameworks>
      net48
    </TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfControl\WpfControl.NetOld.csproj">
      <Name>WpfControl</Name>
      <AssemblyName>WpfControl</AssemblyName>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Models/MySampleModel.vb" />
    <Compile Include="Models/TimeConsumingModel.vb" />

    <Compile Include="Views/MainWindow.xaml.vb" />
    <Compile Include="Views/ProgressWindow.xaml.vb" />
    <Compile Include="Views/SampleWindow.xaml.vb" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="mscorlib" />
  </ItemGroup>

</Project>
