<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViewVb</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>ViewVb</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfControl\WpfControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Models\MatrixDataModel.vb" />
    <Compile Include="Models\MySampleModel.vb" />
    <Compile Include="Models\TimeConsumingModel.vb" />

    <Compile Include="Views\BinaryEditorWindow.xaml.vb" />
    <Compile Include="Views\MainWindow.xaml.vb" />
    <Compile Include="Views\MatrixEditorWindow.xaml.vb" />
    <Compile Include="Views\MatrixViewerWindow.xaml.vb" />
    <Compile Include="Views\ProgressWindow.xaml.vb" />
    <Compile Include="Views\SampleWindow.xaml.vb" />
  </ItemGroup>

</Project>
